### ISSUE TITLE
AttributeError: module 'giniclust3' has no attribute 'gini'

### ISSUE THREAD

**Issue by ghost** [rdong08/GiniClust3#2]
Hi,

I was trying to use GiniClust but this mistake has been appearing several times (AttributeError: module 'giniclust3' has no attribute 'gini'). I tried to install giniclust using conda (conda install -c rdong giniclust3) multiple times but this mistake appeared:
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/rdong/linux-64/current_repodata.json>

So I installed using this other command:
 pip install giniclust3

**Comment by rdong08** [comment]
Thanks a lot for your interest of GiniClust3. The conda may due to the network problem. If conda doesn't work, you please have another try by using 'pip uninstall giniclust3' and reinstall by 'pip install giniclust3'. 
In addition, another way is that 1. git clone https://github.com/rdong08/GiniClust3.git 2. cd GiniClust3 3. python setup.py install

**Comment by ghost** [comment]
The problem that I had was **AttributeError: module 'giniclust3' has no attribute 'gini'** (is the title of the issue)

**Comment by rdong08** [comment]
Could you please share your code?

**Comment by ghost** [comment]
I was trying the example: https://github.com/rdong08/GiniClust3/blob/master/example/MouseBrainCell/performGiniClust3.py
The mistake appeared on line 16

**Comment by rdong08** [comment]
So could you try to uninstall and install it again? I have updated the package recently in pypi.
